#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("idataInCtrl_0", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("idataInCtrl_1", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("idataInCtrl_2", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("idataInCtrl_3", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("fdataInCtrl_0", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("fdataInCtrl_1", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("fdataInCtrl_2", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("fdataInCtrl_3", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("idataOutCtrl_0", 32, hls_out, 8, "ap_none", "out_data", 1),
	Port_Property("idataOutCtrl_1", 32, hls_out, 9, "ap_none", "out_data", 1),
	Port_Property("idataOutCtrl_2", 32, hls_out, 10, "ap_none", "out_data", 1),
	Port_Property("idataOutCtrl_3", 32, hls_out, 11, "ap_none", "out_data", 1),
	Port_Property("fdataOutCtrl_0", 32, hls_out, 12, "ap_none", "out_data", 1),
	Port_Property("fdataOutCtrl_1", 32, hls_out, 13, "ap_none", "out_data", 1),
	Port_Property("fdataOutCtrl_2", 32, hls_out, 14, "ap_none", "out_data", 1),
	Port_Property("fdataOutCtrl_3", 32, hls_out, 15, "ap_none", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "demo_test";
